import 'package:kros6/backend/krosmasters/factory.dart';
import 'package:kros6/backend/krosmasters/krosmaster.dart';
import 'package:kros6/backend/teams/create_random.dart';

class NeniRepository extends KrosmasterRepository {
  @override
  List<Krosmaster> allAvailable() {
    return [
 krosmaster("Otomai"),
 krosmaster("Gein"),
 krosmaster("Thio"),
 krosmaster("Elogio"),
 krosmaster("Ary Saf"),
 krosmaster("Tofu Real"),
 krosmaster("Papatudo Real"),
 krosmaster("Gasper Feyto"),
 krosmaster("Deminobola"),
 krosmaster("Diver Birel"),
 krosmaster("Jordy Ritane"),
 krosmaster("Henual"),
 krosmaster("Barden Tadura"),
 krosmaster("Steamy Wonder"),
 krosmaster("Jeyro Rello"),
 krosmaster("Poochan"),
 krosmaster("Day Kiri"),
 krosmaster("Kivin"),
 krosmaster("Wally Faier"),
 krosmaster("Ostron Doz"),
 krosmaster("Rib ombar"),
 krosmaster("Remington Smif"),
 krosmaster("Zorbalo Greg"),
 krosmaster("Kreol Panikon"),
 krosmaster("Dokdes Tyno"),
 krosmaster("Jems Blond"),
 krosmaster("Gui Yermetel"),
 krosmaster("Ben O Ripata"),
 krosmaster("Henual"),
 krosmaster("Henual"),
 krosmaster("Ayan"),
 krosmaster("Srammy"),
 krosmaster("Vigg Arysta"),
 krosmaster("Ratweyra"),
 krosmaster("Koa Gular"),
 krosmaster("Ana Tomya"),
 krosmaster("Klor Ofila"),
 krosmaster("Makum Bag"),
 krosmaster("Sadida"),
 krosmaster("Quentin Flush"),
 krosmaster("Dany Oshan"),
 krosmaster("Naz Rael"),
 krosmaster("Percimol"),
 krosmaster("Shak Shaka"),
 krosmaster("Cavaleiro Gota"),
 krosmaster("Cavaleiro Chama"),
 krosmaster("Capitão Amakna"),
 krosmaster("Merkator"),
 krosmaster("Rei dos Papatudos"),
 krosmaster("Kanibola Jav"),
 krosmaster("Ruel Stroud"),
 krosmaster("Tristepan"),
 krosmaster("Luk Ylook"),
 krosmaster("Rainha dos Tofus"),
 krosmaster("Yugo"),
 krosmaster("Conde Frigost"),
 krosmaster("Gultar O Bárbaro"),
 krosmaster("Lumino"),
 krosmaster("Korvox"),
 krosmaster("Skalo"),
 krosmaster("Skalo"),
 krosmaster("Skalo"),
 krosmaster("Frondor"),
 krosmaster("Skoria"),
 krosmaster("Sombra"),
 krosmaster("Raul Bek"),
 krosmaster("Katsou Mee"),
 krosmaster("Kitty Rage"),
 krosmaster("Emma Sacre"),
 krosmaster("Bade Barjosa"),
 krosmaster("Mercedes Ligga"),
 krosmaster("Assai Dahy"),
 krosmaster("Pandaysa"),
 krosmaster("Mali Buh"),
 krosmaster("Poochan"),
 krosmaster("Elgward Haporta"),
 krosmaster("Duque Rex"),
 krosmaster("Adamai"),
 krosmaster("Qilby"),
 krosmaster("Riktus de Brakmar"),
 krosmaster("Riktus de Amakna"),
 krosmaster("Riktus de Bonta"),
 krosmaster("Riktus de Elite"),
 krosmaster("Conde Transparent"),
 krosmaster("Rainha dos Ladrões"),
 krosmaster("Grampy"),
 krosmaster("Kerub Crepin"),
 krosmaster("Joris"),
 krosmaster("Lou"),
 krosmaster("Kanibola Arqueiro"),
 krosmaster("Kanibola Sarbak"),
 krosmaster("Kanibola Thierry"),
 krosmaster("Kanibola Phora"),
 krosmaster("Moon"),
 krosmaster("Dragoeth o Pensador"),
 krosmaster("Dralegre a Contente"),
 krosmaster("Dragosa"),
 krosmaster("Omanetta"),
 krosmaster("Boomba"),
 krosmaster("Minotoror"),
 krosmaster("Grougaloragran"),
 krosmaster("Gultar"),
 krosmaster("Diaul"),
 krosmaster("Katar"),
 krosmaster("Vampyro"),
 krosmaster("Corvo Negro"),
 krosmaster("Kriss o Krasso"),
 krosmaster("Vlad Sombrio"),
 krosmaster("Darkli Moon"),
 krosmaster("Ogres criança"),
 krosmaster("Choppy Sue"),
 krosmaster("Tiktokovitch"),
 krosmaster("Bakara"),
 krosmaster("Jahash"),
 krosmaster("Lilota"),
 krosmaster("Julith"),
 krosmaster("Khan Karkass"),
 krosmaster("Miauvô protetor"),
 krosmaster("Marline"),
 krosmaster("Joris espadachim"),
 krosmaster("Chafer lanceiro"),
 krosmaster("Abade Mente"),
 krosmaster("Chafer de Infantaria"),
 krosmaster("Padre Sombrio"),
 krosmaster("Fraderrapada"),
 krosmaster("Milimilobo"),
 krosmaster("Dark Vlad Karnated"),
 krosmaster("Bwork Arqueiro"),
 krosmaster("Groarg Gamel"),
 krosmaster("Medor Thraki"),
 krosmaster("Ko-fang o Branco"),
 krosmaster("Evangelyne"),
 krosmaster("Aly Zelo"),
 krosmaster("Amália"),
 krosmaster("Kip Agau"),
 krosmaster("Merty Olat"),
 krosmaster("Nox"),
 krosmaster("Missiz Frizz"),
    ];
  }
}
